#!/bin/bash
# STATE: ALPHA

#Do not install apt-get version is outdated

/show/description "Install asciidoctor converter"

/show/listecho "Install asciidoctor, this will takes some times" $OK
#We install it with output as it will takes a lot of times
/system/install ruby
/system/install rubygems
gem install asciidoctor


